# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # API Dashboard & Purchasing & RestockAMZ & Administrator & Authenticate
  start-testing-api-without-run-forecast:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: node:14.19.3
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    environment:
      BASE_URL: "https://preprod-my.forecastrx.com"
      DISABLE_UPLOAD: false
    steps:
      - checkout
      - run:
          name: "Test APIs without running forecast"
          command: npm run test-api-without-run-forecast
  # Run forecast for QBFS & CSV companies
  start-testing-api-run-forecast-qbfs-csv:
    docker:
      - image: node:14.19.3
    environment:
      BASE_URL: "https://preprod-my.forecastrx.com"
      DISABLE_UPLOAD: false
    steps:
      - checkout
      - run:
          name: "Test APIs running forecast for QBFS & CSV"
          command: npm run test-api-run-forecast-qbfs-csv
  # Run forecast for ASC companies
  start-testing-api-run-forecast-asc:
    docker:
      - image: node:14.19.3
    environment:
      BASE_URL: "https://preprod-my.forecastrx.com"
      DISABLE_UPLOAD: false
    steps:
      - checkout
      - run:
          name: "Test APIs running forecast for ASC"
          command: npm run test-api-run-forecast-asc

trigger:
  branch:
    - feature/configCI

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  automation-workflow:
    jobs:
      - start-testing-api-without-run-forecast:
          filters:
            branches:
              only:
                - feature/configCI
      - start-testing-api-run-forecast-qbfs-csv:
          filters:
            branches:
              only:
                - feature/configCI
      - start-testing-api-run-forecast-asc:
          filters:
            branches:
              only:
                - feature/configCI