import { z } from 'zod';

//Refer define schema here: https://morioh.com/p/cc9d89e8a10b
export const itemsInPurchasingResponseSchema = z.object({
    addedToSupplies: z.number().optional(),
    asin: z.string().nullable(),
    companyKey: z.string(),
    companyType: z.string(),
    consolidatedQty: z.number(),
    created_at: z.string(),
    daysLeft: z.number().nullable(),
    daysRemaining: z.number().nullable(),
    daysUntilNextScheduledOrder: z.number().nullable(),
    description: z.string().nullable(),
    documentUuid: z.string().nullable(),
    dueDate: z.string(),
    fnsku: z.string().nullable(),
    imageUrl: z.string().nullable(),
    inbound: z.number(),
    inboundAlert: z.string().nullable(),
    inboundAvailable: z.number(),
    inboundCustomerOrder: z.number(),
    inboundFcProcessing: z.number(),
    inboundFcTransfer: z.number(),
    inboundPrice: z.number(),
    inboundSalesLast30Days: z.number(),
    inboundUnfulfillable: z.number(),
    inboundWorking: z.number(),
    inventorySourcePreference: z.string().nullable(),
    isFbm: z.boolean(),
    itemKey: z.string(),
    itemName: z.string().nullable(),
    lastOrderDate: z.string().nullable(),
    leadTime: z.number(),
    lotMultipleQty: z.number(),
    meanLtd: z.number(),
    moq: z.number(),
    mwsFulfillmentFee: z.number(),
    nextScheduledOrderDate: z.string().nullable(),
    onHand: z.number(),
    onHandFbm: z.number(),
    onHandMin: z.number(),
    onHandThirdParty: z.number(),
    onHandThirdPartyMin: z.number(),
    onNewPo: z.number(),
    openPurchaseOrders: z.number(),
    openSalesOrders: z.number(),
    orderInterval: z.number(),
    outOfStockDate: z.string().nullable(),
    purchaseQty: z.number(),
    purchasingSummariesUuid: z.string().uuid(),
    recommendedOrderDate: z.string().nullable(),
    recommendedQty: z.number(),
    s7d: z.number(),
    s30d: z.number(),
    s90d: z.number(),
    s365d: z.number(),
    sMtd: z.number(),
    sYtd: z.number(),
    s_2d: z.number(),
    s_180d: z.number(),
    s_60d: z.number(),
    safetyStockLtd: z.number(),
    snapshotQty: z.number(),
    tags: z.array(z.string().nullable()),
    total: z.number(),
    trueRecommendedQty: z.number().nullable(),
    vendorPrice: z.number(),
    type: z.string(),
    updated_at: z.string(),
    vendorKey: z.string().nullable(),
    vendorName: z.string().nullable(),
});

export const resultsResponseSchema = z.object({
    err: z.string().nullable(),
    model: z.object({
        companyKey: z.string(),
        companyType: z.string(),
        historySnapshot: z.array(z.number().nullable()),
        itemKey: z.string(),
        itemName: z.string(),
        leadTime: z.number(),
        meanForecast: z.array(z.number().nullable()),
        orderInterval: z.number(),
        safetyStockForecast: z.array(z.number().nullable())
    })
});